services:
  db:
    image: postgres:18.6-alpine3.24
    container_name: twitch-clone-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/18/docker
    networks:
      - backend
    restart: unless-stopped
  redis:
    image: redis:7-alpine3.21
    container_name: twitch-clone-cache
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASS}
    volumes:
      - redis-data:/data
    networks:
      - backend
    restart: unless-stopped
volumes:
  pgdata:
  redis-data:
networks:
  backend: